### ISSUE TITLE
Log utils writer

### ISSUE THREAD

**Issue by Fimeo** [hashicorp/logutils#11]
Hi !

I'm using your log library because of it's simplicity. But I noticed that, when the writer output is a file, if the log file has been deleted during run time, there is no error returned by logutil.

Did they have any way to receive an event when the log utils cannot write in the output ?

Thx a lot

Fimeo

**Comment by julio77it** [comment]
Hi, 

I think you can answer to your question here : https://stackoverflow.com/questions/2028874/what-happens-to-an-open-file-handle-on-linux-if-the-pointed-file-gets-moved-or-d

"If the file is deleted, the file handle remains open and can still be used (This is not what some people expect). The file will not really be deleted until the last handle is closed."

Giulio
