### ISSUE TITLE
Would it make sense to print the stack when logging in certain levels? Ex: on error logging

### ISSUE THREAD

**Issue by c4milo** [hashicorp/logutils#4]
I've been feeling the need to output the stack upon errors so I can quickly find the source of issues. I've been printing the stack next to the logging line but it seems like this could be automatically done by logutils based on the level. How are you guys doing this?

**Comment by kylewolfe** [comment]
Hi Camilo, would this be a parameter of LevelFilter or hard coded in?

**Comment by c4milo** [comment]
A parameter somewhere.

**Comment by josephholsten** [comment]
Similar projects have a spot between the log-filtering component and the log-writing component. I'm inclined to prefer this be part of a log writer.

Also, I haven't a clue how to make an arbitrary `log.Printf()` yield up a stack trace. Any ideas on how we might implement that?

**Comment by jefferai** [comment]
hclog does it, you might want to look there for guidance.

**Comment by mitchellh** [comment]
Closing this since we've moved on mostly.
